### PR TITLE
Add layer meta-rauc-qemuarma9

### PR DESCRIPTION
**Pull request by minkosimon**

### CODE REVIEW

**Comment by leon-anavi** [comment]
Hi @minkosimon,

Thank you for this pull request. A couple of questions based on my first look at the source code:

* Is it based on the existing BSP layer [meta-qemuarma9](https://github.com/OverC/meta-qemuarma9)? If yes, why are machine configurations and general BSP recipes part of meta-rauc-qemuarma9? In my opinion meta-rauc-* layers should be as simple as possible by building on top of the existing BSP and adding only specific bits for the RAUC integration.

* Could you please adjust the "Copyright (C)" headers in the files because meta-rauc-community is available under MIT license?

Thanks,
Leon

**Comment by minkosimon** [comment]
Hello Leon, Thank you for your comments. I will change it.

**Comment by minkosimon** [comment]
Leon my layer is  based on [meta-qemuarma9](https://github.com/ahmedkassem56/meta-qemuarma9) adapted by ahmedkassem56. The main idea was called machine qemuarma9 with right recipes. I will change it

**Comment by leon-anavi** [comment]
@minkosimon  one more thing, a CI check is failing. Please include a Signed-off-by line in all commit messages.

Thanks,
Leon

**Comment by ejoerns** [comment]
Thanks for the contribution @minkosimon, but indeed this layer still adds too much overhead.

Configurations for graphics, etc. is not required for RAUC.

Also, Qemu machines are provided by oe-core and we should use these.

I would tend to propose rejecting this and encouraging starting a layer against oe-core kirkstone/master from scratch.

**Comment by leon-anavi** [comment]
Hi @minkosimon, @ejoerns,

Thank you all for the contributions. It looks like there is no recent development on this pull request. Although I see there has been a lot of good work done here, considering meta-rauc-qemuarma9 should be split to use meta-qemuarma9 as a BSP layer I agree with @ejoerns to reject it at the moment. I also encourage starting a layer against oe-core kirkstone/master from scratch.

Best regards,
Leon

**Comment by minkosimon** [comment]
Hello @leon-anavi and @ejoerns 

I haven't time to update my changes and take account your suggestions since last time. I just start a new position.
Ok to reject my previous commit.
As @leon-anavi  suggest, I'll start from scratch by starting a layer against oe-core kirkstone/master from scratch.
may be I'll need support, to be sure I respect your process.
Thank you for your time and wish you the best for 2023

**Pull request closed without merging**
