### PR TITLE
qemux86 for dunfell branch

### PR DESCRIPTION
**Pull request by Vladimir-Dragunov**
In my work practice I got task, set compatible this machine qemux86 for dunfell version.
All works fine.

All changes from master qemux86:

**meta-rauc-qemux86/conf/layer.conf**

+ LAYERSERIES_COMPAT_meta-rauc-qemux86 = "dunfell"

**meta-rauc-qemux86/kas-qemu-grub.yml**

+ machine: qemux86
 
+ refspec: "refs/remotes/origin/dunfell"

**meta-rauc-qemux86/recipes-core/rauc/rauc_%.bbappend**

+ FILESEXTRAPATHS:prepend := " ${THISDIR}/files/qemux86:"

+ SRC_URI:append := " file://system.conf"

**meta-rauc-qemux86/recipes-core/rauc/files/qemux86/system.conf**

+ compatible=qemu86 demo platform

**meta-rauc-qemux86/recipes-core/bundles/qemu-demo-bundle.bb**

+ RAUC_BUNDLE_COMPATIBLE = "qemu86 demo platform"

**meta-rauc-qemux86/recipes-bsp/boot-image/boot-image.bb**

+ cp ${DEPLOY_DIR_IMAGE}/grub-efi-bootia32.efi ${FATSOURCEDIR}/EFI/BOOT/bootia32.efi

Signed-off-by: Vladimir Dragunov contact.dragunov@gmail.com

### CODE REVIEW

**Comment by leon-anavi** [comment]
Hi @Vladimir-Dragunov,

Thank you for your contribution. Sounds good to me to merge the QEMUx86 in the `dunfell` branch. @ejoerns should we proceed with merging it?

Thanks,
Leon

**Comment by ejoerns** [comment]
@Vladimir-Dragunov In how far does this differ from the version in master? This is just a dump. Please either add a slightly descriptive commit message (with signed-of-by) or just cherry-pick the original patches. The commit does not even describe the source of the changes which is probably master. This will make it hard to say later if we have to backport anything.

**Comment by Vladimir-Dragunov** [comment]
Ok, sounds good.
Can I describe changes in comments?

Sorry, I did really dumb move where just copypaste qemux86 from master branch in dunfell and changing it without commiting changes in git :C

**Comment by ejoerns** [comment]
> Ok, sounds good. Can I describe changes in comments?

A commit message can be a short book. So, yes :grin: 

A valid signed-of-by line you can get when invoking `git commit` with `-s` switch.

> Sorry, I did really dumb move where just copypaste qemux86 from master branch in dunfell and changing it without commiting changes in git :C

This is not really how FOSS-quality software development works :smirk: 
Maybe at cherry-pick the patches to get a copy of the original content and then copy your state over it. This should at least produce a commit describing the differences. Then we may see how to proceed.

**Pull request closed without merging**
